---
name: CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Check Python
        run: |
          python3.12 --version
          python3.12 -m pip --version

      - name: install dependencies
        run: |
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install -r requirements.txt

      - name: testing
        run: |
          python3.12 -m unittest discover tests

  deploy:
    needs: test
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
      - name: deploying application
        run: |
          echo "deploying application"
          python3.12 run.py
